name: Deploy Frontend

on:
  push:
    branches: [ master ]  # Cambiado de main a master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/app-frontend
            cd ~/app-frontend
            
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              # Cambiado de main a master aquí también
              git fetch origin master
              git reset --hard origin/master
            fi

            echo "${{ secrets.DOTENV_FILE }}" > .env
            sudo docker compose up -d --build